resources:
- name: ops.git
  type: git
  source:
    branch: master
    private_key: {{ops-git-deploy-key}}
    uri: {{ops-git-uri}}
- name: acme-proxy-boshrelease.git
  type: git
  source:
    branch: ci #TODO can change to master after merge
    uri: https://github.com/govau/acme-proxy-boshrelease.git
- name: certs-d.s3
  type: s3
  source:
    bucket: {{aws-bucket-d}}
    region_name: ap-southeast-2
    versioned_file: certs.tar.gz
    access_key_id: {{aws-access-key-id-d}}
    secret_access_key: {{aws-secret-access-key-d}}
    server_side_encryption: AES256
- name: release-d.s3
  type: s3
  source:
    bucket: {{aws-bucket-d}}
    region_name: ap-southeast-2
    versioned_file: release.tar.gz
    access_key_id: {{aws-access-key-id-d}}
    secret_access_key: {{aws-secret-access-key-d}}
    server_side_encryption: AES256
jobs:
- name: create-d
  plan:
  - aggregate:
    - get: acme-proxy-boshrelease.git
    - get: ops.git
    - get: certs.s3
      resource: certs-d.s3
  - task: create-release
    file: acme-proxy-boshrelease.git/ci/tasks/create-release.yml
  - put: release-d.s3
    params:
      file: releases/release.tar.gz
